# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  Repository: repository  # github repositories
  # Books: books  # 豆瓣书单
  Links: links  # 友链
  About: about  # 关于
  Algorithms: https://algorithm.iwwee.com

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill
  algorithms: icon-folder

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/2993320.jpg
  title: kajweb的博客 # 页面title
  favicon: /favicon.png
  board: <p><a href="https://blog.csdn.net/kajweb">原博客</a>　/　<a href="https://github.com/kajweb">github</a></p> # 站点公告
  copyright: false # 底部版权信息
  publishby: false

# config
config:
  skin: # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: false # 是否开启当前菜单高亮显示
  thumbnail: false # enable posts thumbnail, options: true, false
  excerpt_link: Read More

# Pagination
pagination:
  number: false
  prev: 
    alwayShow: true
  next:
    alwayShow: true

# Sidebar
sidebar: right
widgets:
  - board  
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
archive_type: 'monthly'
show_count: true

# Fancybox
fancybox: false

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: true
  # 微信打赏
  wechatpay:
    qrcode: images/donate/wc.png
    title: 微信支付
  # 支付宝打赏
  alipay: 
    qrcode: images/donate/al.png 
    title: 支付宝

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: true  # 是否启用分享
  # sites: weibo,qq,wechat,facebook,twitter  # PC端显示的分享图标
  sites: qq,qzone,wechat,weibo,douban,facebook,twitter,google,linkedin  # PC端显示的分享图标
  mobile_sites: wechat,qq,qzone,weibo  # 移动端显示的分享图标

# Github
github: 
  username: kajweb  # github username
  organization: WXA-IDE

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  type:   # 启用哪种评论系统
  disqus:  # enter disqus shortname here
  youyan: 
    uid: 1783844 # enter youyan uid 
  livere:
    uid: # enter youyan uid 
  gitment:
    githubID: 
    repo: 
    ClientID: 
    ClientSecret: 
    lazy: false
  gitalk: # gitalk. https://gitalk.github.io/
    owner:  #必须. GitHub repository 所有者，可以是个人或者组织。
    admin:  #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo:  #必须. GitHub repository.
    ClientID:  #必须. GitHub Application Client ID.
    ClientSecret:  #必须. GitHub Application Client Secret.
  valine: # Valine. https://valine.js.org
    appid:  # your leancloud application appid
    appkey:  # your leancloud application appkey
    notify: false # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: Just go go # comment box placeholder
    avatar: mm # gravatar style
    meta: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    visitor: false # Article reading statistic https://valine.js.org/visitor.html

# douban 豆瓣书单
# Api：
  # https://developers.douban.com/wiki/?title=book_v2 图书
  # https://developers.douban.com/wiki/?title=movie_v2 电影
# books：  
  # https://api.douban.com/v2/book/user/:name/collections?start=0&count=100 个人书单列表
# movies: 
  # https://api.douban.com/v2/movie/in_theaters 正在上映的电影
  # https://api.douban.com/v2/movie/coming_soon 即将上映的电影
  # https://api.douban.com/v2/movie/subject/:id 单个电影信息
  # https://api.douban.com/v2/movie/search?q={text} 电影搜索
douban:
  user: # 豆瓣用户名
  start: 0 # 从哪一条记录开始
  count: 100 # 获取豆瓣书单数据条数
  
# PV
pv:
  busuanzi:
    enable: false  # 不蒜子统计
  leancloud:
    enable: true  # leancloud统计
    app_id: # leancloud <AppID>
    app_key: # leancloud <AppKey>

loger:
  leancloud:
    enable: false  # leancloud统计
    app_id: # leancloud <AppID>
    app_key: # leancloud <AppKey>
        
# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计 

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics: 
  
# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  
  
# profile
profile:
  enabled: true # Whether to show profile bar
  avatar: images/2993320.jpg
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: kajweb
  author_title: Full Stack Programmer
  author_description: welcome to https://iwwee.com
  location: Guangdong, China
  follow: https://github.com/kajweb
  # Social Links
  social:
    links:
      github: https://github.com/kajweb
      weibo: https://weibo.com/ismylyy
      # twitter: https://twitter.com/iwebued
      # facebook: /
      # dribbble: /
      # behance: https://www.behance.net/cofess
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills 
  skills:
    Git: ★★★★☆
    Gulp: ★★☆☆☆
    Javascript: ★★★★★
    HTML+CSS: ★★★★★
    Bootstrap: ★★☆☆☆
    ThinkPHP: ★★★★☆
    平面设计: ★★★☆☆
  # My Personal Links
  links:
    Github: https://github.com/kajweb
    Blog: https://iwwee.com
    微博: https://weibo.com/ismylyy
  # My Personal Labels
  labels:
    - 前端
    - 前端开发
    - 前端重构
    - Web前端
    - 网页重构
  # My Personal Works
  works:
    Qingting Technology Co., Ltd.:
      link: https://qinng.cn/
      date: 2017-2019
  # My Personal Projects
  projects:
    kajweb/wqxuetang_downloader: https://github.com/kajweb/wqxuetang_downloader
    kajweb/douyin_downloader: https://github.com/kajweb/douyin_downloader
    kajweb/image-cycle-resizer: https://github.com/kajweb/image-cycle-resizer

#备案号
beian: 粤ICP备18116211号

codeblock: 
  copy_button: 
    enable: true
    result: true
  copyright:
    enable: true
    content: \n/**\n* 感谢您复制代码，使用代码请注明引用出处\n* kajweb @ https://blog.iwwee.com\n*/
